name: Semantic Release

on:
  push:
    # These are the branches that we expect to publish from
    # semantic-release also has a regex that validates we're running on a release branch
    branches:
      - master
      - "[0-9]+.x"
      - "[0-9]+.x.x"
      - "[0-9]+.[0-9]+.x"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: ">=14.16.0 14"
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          GIT_COMMITTER_NAME: samtjo
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
