name: Semantic Release

on:
  push:
    # These are the branches that we expect to publish from
    # semantic-release also has a regex that validates we're running on a release branch
    branches:
      - master
      - "[0-9]+.x"
      - "[0-9]+.x.x"
      - "[0-9]+.[0-9]+.x"

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versionNumber.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: ">=14.16.0 14"
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          GIT_COMMITTER_NAME: samtjo
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
      - run: echo "$SEMVER_VERSION"
      - id: versionNumber
        run: echo "::set-output name=version::$SEMVER_VERSION"

  publish:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.version != null }}
    steps:
      - run: echo ${{needs.release.outputs.version}}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: ">=14.16.0 14"
      - run: npm ci
      - run: NODE_ENV=production npm run build-storybook
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - run: aws s3 sync ./storybook-static/ s3://carbon-versioned/archive/v${{needs.release.outputs.version}}
